config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :products do
      resources :digitals
    end

    resources :orders do
      member do
        get :reset_digitals
      end
    end
  end

  get '/digital/:secret', to: 'digitals#show', as: 'digital', constraints: { secret: /[a-zA-Z0-9]{30}/ }
end

app/models/spree/digital.rb
module Spree
  class Digital < ActiveRecord::Base
    belongs_to :variant
    has_many :digital_links, dependent: :destroy

    has_one_attached :attachment
    validates :attachment, attached: true
  end
end

app/models/spree/stock/splitter/digital.rb
module Spree
  module Stock
    module Splitter
      class Digital < Base
        def split(packages)
          split_packages = []
          packages.each do |package|
            split_packages += split_by_digital(package)
          end
          return_next split_packages
        end

        private

        def split_by_digital(package)
          digitals = Hash.new { |hash, key| hash[key] = [] }
          package.contents.each do |item|
            digitals[item.variant.digital?] << item
          end
          hash_to_packages(digitals)
        end

        def hash_to_packages(digitals)
          packages = []
          digitals.each do |_id, contents|
            packages << build_package(contents)
          end
          packages
        end
      end
    end
  end
end

app/controllers/spree/admin/digitals_controller.rb
module Spree
  module Admin
    class DigitalsController < ResourceController
      belongs_to 'spree/product', find_by: :slug

      def create
        invoke_callbacks(:create, :before)
        @object.attributes = permitted_resource_params
        @object.attributes = add_additional_paramas if params[:digital][:attachment]

        if @object.valid?
          super
        else
          invoke_callbacks(:create, :fails)
          flash[:error] = @object.errors.full_messages.join(', ')
          redirect_to location_after_save
        end
      end

      protected

      def location_after_save
        spree.admin_product_digitals_path(@product)
      end

      def permitted_resource_params
        params.require(:digital).permit(permitted_digital_attributes)
      end

      def permitted_digital_attributes
        %i[variant_id attachment attachment_file_name attachment_content_type]
      end

      def add_additional_paramas
        hash = {}
        hash[:attachment_file_name] = params[:digital][:attachment].original_filename
        hash[:attachment_content_type] = params[:digital][:attachment].content_type
        hash
      end
    end
  end
end

app/controllers/spree/digitals_controller.rb
module Spree
  class DigitalsController < ApplicationController
    def show
      if attachment.present?
        if digital_link.authorize!
          if Rails.application.config.active_storage.service == :amazon
            redirect_to attachment.expiring_url(Spree::DigitalConfiguration[:s3_expiration_seconds]) and return
          else
            send_file(
              ActiveStorage::Blob.service.path_for(attachment.key),
              filename: attachment.record.attachment_file_name,
              type: attachment.record.attachment_content_type,
              status: :ok
            ) and return
          end
        end
      else
        Rails.logger.error 'Missing Digital Item: attachment'
      end

      render :unauthorized
    end

    private

    def digital_link
      @link ||= DigitalLink.find_by!(secret: params[:secret])
    end

    def attachment
      @attachment ||= digital_link.digital.try(:attachment) if digital_link.present?
    end
  end
end

app/views/spree/admin/digitals/_digital.html.erb
<% if digital.attachment_file_name.present? %>
  <strong><%= digital.attachment_file_name %></strong>
  (<%= number_to_human_size(digital.attachment_file_size) %>)
<% else %>
  <%= Spree.t(:broken_file, scope: 'digitals') %>
<% end %>

app/views/spree/admin/digitals/_form.html.erb
<div>
  <%= form_for(:digital, :url => admin_product_digitals_path(@product), :method => :create, :multipart => true ) do |f| %>
    <fieldset>
      <legend class='h4 pl-0 <%= variant.digital? ? "mb-0" : "mb-3" %>'><%= Spree::Variant.model_name.human %> "<%= variant.is_master ? "Master" : variant.options_text %>"</legend>
      <% if variant.digital? %>
        <table class="table">
          <thead>
            <tr>
              <th><%= Spree.t(:file_name, scope: "spree_digital") %></th>
              <th class="actions"></th>
            </tr>
          </thead>
          <tbody>
          <% variant.digitals.each do |digital| %>
            <tr>
              <td><%= render digital %></td>
              <td class="actions text-right">
                <%= link_to_with_icon 'delete', Spree.t(:delete_file, scope: 'digitals'), admin_product_digital_url(@product, digital), data: {confirm: Spree.t(:delete_file_confirmation, scope: 'digitals', filename: digital.attachment_file_name)}, method: :delete, class: 'btn btn-danger btn-sm delete-resource' %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      <% end %>

      <div class="form-group">
        <%= f.label :file, Spree.t(:add_new_file, scope: 'digitals') %> <span class="required">*</span><br/>
        <%= f.file_field :attachment %>
        <%= hidden_field_tag 'digital[variant_id]', variant.id %>
        <%= button Spree.t(:upload, scope: "spree_digital"), 'add', 'submit', { :class => "btn btn-primary" } %>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/spree/admin/digitals/_sample_form.html.erb
<div>
  <div>
    <%= form_for(:digital_sample, :url => { :controller => 'digital_samples', :action => 'create' }, :html => { :multipart => true }) do |f| %>
    <fieldset>
      <legend><%= Spree::Variant.model_name.human %> "<%= variant.options_text %>"</legend>
      
      <%= f.field_container :current_file do %>
      <strong><%=t 'Free Files' %>:</strong>
      <% if variant.digital_sample? %>
      <ul>
        <% variant.digital_samples.each do |digital_sample| %>
        <li>
         <%= render digital_sample %>&nbsp;&nbsp;
         <%= link_to t("delete_file"), admin_product_digital_sample_url(:id => digital_sample.id), :confirm => t('delete_file_confirmation', :filename => digital_sample.attachment_file_name), :method => :delete %>
       </li>
       <% end %>
     </ul>
     <% else %>
     <%=t 'none' %>
     <% end %>
     <% end %>

     <p class="form-buttons">
      <%= f.field_container :file do %>
      <%= f.label :file, t("new_file") %> <span class="required">*</span><br/>
      <%= f.file_field :attachment %>
      <% end %>

      <%= hidden_field_tag 'digital_sample[variant_id]', variant.id %>

      <%= button t('spree_digital_sample.upload') %>
    </p>

  </fieldset>
  <% end %>
</div>

app/views/spree/admin/digitals/index.html.erb
<%= render :partial => 'spree/admin/shared/sub_menu/product' %>
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => "Digital Versions"} %>

<% if @product.has_variants? %>

  <% for variant in @product.variants_including_master do %>
    <%= render 'form', :variant => variant %>
  <% end %>

<% else %>
  <p><%= Spree.t('product_has_no_variants') %><p>

  <% if @product.master.digital? %>
    A digital version of this product currently exists:
    <%= render @product.master.digitals %>
  <% end %>

  <%= render 'form', :variant => @product.master %>

<% end %>